### PR TITLE
updated starting point to Swift 3

### PR DESCRIPTION
**Pull request by skylarhansen**

### CODE REVIEW

**Comment by skylarhansen** [comment]
@armadsen

**Review by armadsen — DISMISSED** [review]
Skylar, looks like this PR has merge conflicts too. Can you fix those?

**Comment by skylarhansen** [comment]
@armadsen these changes were for the start of the project. There are some files that the students are supposed to start off with. In the master repo the start, part1solution, and part2solution are all tags, not branches, but I didn't know how to create PRs on tags. Is that even possible? I'm just wondering if I resolve the conflicts here, wouldn't it mess up the master copy? A lot of the files are missing in this commit from the master copy since it's the starting point. If I'm mistaken and you still need me to resolve these conflicts I can. Just let me know

**Comment by armadsen** [comment]
@skylarhansen Can you change this to target the projectStart branch?

**Comment by skylarhansen** [comment]
@armadsen This should be working now

**Pull request closed without merging**
